Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KimDongBookStore.Models;

namespace KimDongBookStore.Controllers
{
    public class NguoiDungController : Controller
    {
        KimDongBookStoreDataContext db = new KimDongBookStoreDataContext();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult DangNhap()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection col)
        {
            var taikhoan = col["taikhoan"];
            var matkhau = col["matkhau"];
            KHACHHANG kh = db.KHACHHANGs.Where(a => a.TAIKHOAN == taikhoan && a.MATKHAU == matkhau).FirstOrDefault();
            if(kh == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                Session["taikhoan"] = kh;
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult DangKy()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult DangKy(FormCollection col)
        {
            var hoten = col["hoten"];
            var taikhoan = col["taikhoan"];
            var dienthoai = col["dienthoai"];
            var email = col["email"];
            var matkhau = col["matkhau"];
            var diachi = col["diachi"];
            //tao khach hang moi
            KHACHHANG kh = new KHACHHANG();
            kh.HOTEN = hoten;
            kh.TAIKHOAN = taikhoan;
            kh.MATKHAU = matkhau;
            kh.DIENTHOAI = dienthoai;
            kh.EMAIL = email;
            kh.DIACHI = diachi;
            db.KHACHHANGs.InsertOnSubmit(kh);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TaiKhoan()
        {
            KHACHHANG kh = (KHACHHANG)Session["taikhoan"];
            return PartialView(kh);
        }

        public ActionResult DangXuat()
        {
            Session["taikhoan"] = null;
            return PartialView();
        }
    }
}

Views/NguoiDung/DangKy.cshtml
<style>
    form input, form select {
        padding: 8px 20px;
        margin: 5px 0;
        width: 100%;
    }

    .btn-login {
        font-size: 12px;
        padding: 8px 10px;
        margin: 5px 12px;
        width: 50%;
    }

    form .btn-login {
        border-radius: 0 !important;
        width: 100%;
    }

    .form-login {
        display: flex;
        flex-direction: column;
    }
</style>

<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel2">Xin chào</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-8">
                        <p>
                            <span style="color: #d51c24; cursor: pointer;" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Đăng nhập</span>
                            hoặc
                            <span style="color: #d51c24;">Tạo tài khoản</span>
                        </p>
                        @using (Html.BeginForm("DangKy", "NguoiDung", FormMethod.Post, new { @class = "form-login" }))
                        {
                            @Html.ValidationSummary(true)
                            {
                                <input type="text" placeholder="Họ tên" name="hoten" required/>
                                <input type="text" placeholder="Tài khoản" name="taikhoan" required/>
                                <input type="tel" placeholder="Số điện thoại" name="dienthoai"/>
                                <input type="text" placeholder="diachi" name="diachi" />
                                <input type="email" placeholder="customer.register.email" name="email"/>
                                <input type="password" placeholder="customer.register.password" name="matkhau" required/>
                                <select name="gioitinh">
                                    <option>Nam</option>
                                    <option>Nữ</option>
                                </select>
                                <label>Ngày sinh</label>
                                <input type="date" name="ngaysinh"/>
                                <div class="d-flex mb-3">
                                    <input type="checkbox" style="width: fit-content; margin: 10px;" checked/>
                                    <span>Nhận thông tin và chương trình khuyến mãi của NXB Kim Đồng qua Email</span>
                                </div>
                                <button class="btn btn-danger btn-login m-0" type="submit">Đăng Ký</button>
                            }
                        }
                    </div>
                    <div class="col-4 d-flex justify-content-center">
                        <img src="/Content/img/logo.png" class="d-block w-25" style="object-fit: contain;" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a class="col-md-3 d-flex justify-content-center align-items-center text-decoration-none text-dark" data-bs-toggle="modal" href="#exampleModalToggle2" role="button">
    <ion-icon name="person-add-outline" class="me-1"></ion-icon>
    <span class="text-icon">
        Đăng ký
    </span>
</a>

Views/NguoiDung/DangNhap.cshtml
<style>
    form input {
        padding: 8px 20px;
        margin: 5px 0;
        width: 100%;
    }

    .btn-login {
        font-size: 12px;
        padding: 8px 10px;
        margin: 5px 12px;
        width: 50%;
    }

    form .btn-login {
        border-radius: 0 !important;
        width: 100%;
    }
</style>

<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel">Đăng ký</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-8">
                            <h6>Xin chào,</h6>
                            <p>
                                <span style="color: #d51c24; border: none !important; outline: none !important;">Đăng nhập</span>
                                <span>
                                    hoặc
                                </span>
                                <span style="color: #d51c24; cursor:pointer;" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">tạo tài khoản</span>
                            </p>
                            <form method="POST" action="/NguoiDung/DangNhap" class="d-flex flex-column align-items-center w-100">
                                <input name="taikhoan" class="input" placeholder="Tên đăng nhập" />
                                <input name="matkhau" type="password" class="input" placeholder="Mật khẩu" />
                                <button class="btn btn-danger d-block btn-login" type="submit">Đăng nhập</button>
                            </form>
                            <div class="row justify-content-center">
                                <button class="col btn btn-danger btn-login">Đăng nhập Google</button>
                                <button class="col btn btn-info btn-login">Đăng nhập facebook</button>
                            </div>
                        </div>
                        <div class="col-4 d-flex justify-content-center">
                            <img src="/Content/img/logo.png" class="d-block w-25" style="object-fit: contain;" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a class="col-md-3 d-flex justify-content-center align-items-center text-decoration-none text-dark" data-bs-toggle="modal" href="#exampleModalToggle" role="button">
    <ion-icon name="log-in-outline" class="me-1"></ion-icon>
    <span class="text-icon">
        Đăng nhập
    </span>
</a>

Views/NguoiDung/DangXuat.cshtml
<a class="col-md-3 d-flex justify-content-center align-items-center text-decoration-none text-dark" href="/">
    <ion-icon name="log-out-outline"></ion-icon>
    <span class="text-icon">
        Đăng xuất
    </span>
</a>

Views/NguoiDung/Index.cshtml
<div style="color: green;">THANH COONG</div>

Views/NguoiDung/TaiKhoan.cshtml
<div class="col-md-3 d-flex justify-content-center align-items-center text-decoration-none">
    <ion-icon name="person-outline"></ion-icon>
    <span class="text-icon">
        @Model.HOTEN
    </span>
</div>